language: c
# Check available binaries before updating the build matrix
matrix:
  include:
  - os: osx
    osx_image: xcode10.3
  - os: osx
    osx_image: xcode9.4
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode7.3
  allow_failures:
  - os: osx
    osx_image: xcode8.3
  - os: osx
    osx_image: xcode7.3
env:
- COLUMNS=78
before_install:
- ./_ci/bootstrap.sh
- unset CC && source /opt/local/share/macports/setupenv.bash
- export PATH="/opt/mports/bin:${PWD}/../mpbb:$PATH" && hash -r
script:
- sudo ./runner
notifications:
  webhooks: https://infra.macports.org/pr-bot/travis
