trigger: none

jobs:

- job: Build
  timeoutInMinutes: 0

  strategy:
    matrix:
      mac-10.14:
        imageName: 'macOS-10.14'
      mac-10.13:
        imageName: 'macOS-10.13'
  pool:
    vmImage: $(imageName)

  steps:
  - checkout: self
    fetchDepth: 64

  - script: ./_ci/bootstrap.sh
    displayName: 'Run bootstrap script'

  - script: |
      unset CC && source /opt/local/share/macports/setupenv.bash
      export PATH="/opt/mports/bin:${PWD}/../mpbb:$PATH" && hash -r
      sudo env PASTE_URL="$PASTE_URL" ./runner
    displayName: 'Run port tests'
