trigger: none

pool:
  vmImage: 'macOS-10.13'

steps:
- script: ./_ci/bootstrap.sh
  displayName: 'Run bootstrap script'

- script: |
    unset CC && source /opt/local/share/macports/setupenv.bash
    export PATH="/opt/mports/bin:${PWD}/../mpbb:$PATH" && hash -r
  displayName: 'Setup environment'

- script: sudo ./runner
  displayName: 'Run port tests'
